=== sel596xml/TEIDict/sel596.dtd
<!ELEMENT TEI (teiHeader|text)*>
<!ATTLIST TEI xmlns CDATA #REQUIRED>
<!ELEMENT teiHeader (fileDesc)*>
<!ELEMENT fileDesc (titleStmt|publicationStmt|sourceDesc)*>
<!ELEMENT titleStmt (title)*>
<!ELEMENT title (#PCDATA)>
<!ELEMENT publicationStmt (p)*>
<!ELEMENT p (#PCDATA)>
<!ELEMENT sourceDesc (p)*>
<!ELEMENT text (body)*>
<!ELEMENT body (entry)*>
<!ELEMENT entry (form|gramGrp|sense|def|xr|cit)*>
<!ELEMENT form (orth|lang)*>
<!ELEMENT orth (#PCDATA)>
<!ELEMENT lang (#PCDATA)>
<!ELEMENT gramGrp (#PCDATA|colloc|pos|etym|sense|def)*>
<!ELEMENT colloc (#PCDATA)>
<!ELEMENT sense (#PCDATA|def|sense|gramGrp)*>
<!ATTLIST sense n CDATA #REQUIRED>
<!ELEMENT def (#PCDATA|bibl|cit|xr)*>
<!ATTLIST def n CDATA #IMPLIED>
<!ELEMENT bibl (#PCDATA|author)*>
<!ELEMENT author (#PCDATA)>
<!ELEMENT pos (#PCDATA)>
<!ELEMENT xr (#PCDATA)>
<!ELEMENT cit (quote|bibl)*>
<!ELEMENT quote (#PCDATA)>
<!ELEMENT etym (#PCDATA)>

=== sel596xml/TEIDict/sel596.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.tei-c.org/release/xml/tei/custom/schema/relaxng/tei_all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-stylesheet type="text/xsl" href="sel596.xsl"?>
<!DOCTYPE TEI SYSTEM "sel596.dtd">
<TEI xmlns="http://www.tei-c.org/ns/1.0">
   <teiHeader>
        <fileDesc>
            <titleStmt>
                <title>TEI Dict Page 596</title>
             </titleStmt>
        </fileDesc>
   </teiHeader>
   <text>
        <body>      
                
            <entry>
                <form>
                    <orth>ἱεροφαντία, ας</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ἡ</colloc>
                </gramGrp>
                <sense n="1">
                    <def>
                        office of ἱεροφάντης. <bibl><author>Plut. I</author>, 210 C. <author>II</author>, 621 C.</bibl>
                    </def>
                </sense>
                <sense n="2">
                    <def>
                        A revealing of sacred things. <bibl><author>Clem. A. I</author>, 112 C. 1216 C.</bibl>
                    </def>
                </sense>
            </entry>
  
            <entry>
                <form>
                    <orth>
                        ἱεροφαντικός, ή, όν
                    </orth>
                    <lang>GR</lang>
                </form>
                <def>
                    hirophantic. <bibl><author>Plut. I</author>, 74 E. <author>Lucian. II</author>, 264. <author>Clem. A. Ι</author>, 84 A.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱεροφαντικῶς</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <pos>adv.</pos>
                </gramGrp>
                <def>
                    like a hierophant. <bibl><author>Lucian. II</author>, 246.</bibl>
                </def>
            </entry>

            <entry>
                <form>
                    <orth>ἱεροφάντωρ, ορος</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ὁ</colloc>
                </gramGrp>
                <def>
                    ἱεροφάντης. <bibl><author>Epiph. II</author>, 741 D, Moses</bibl>.
                </def>
            </entry>

            <entry>
                <form>
                    <orth>ἱεροφοιτέω, ήσω</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>(φοιτάω)</colloc>
                </gramGrp>
                <def>
                    to frequent temples. <bibl><author>Ptol.</author> 158.</bibl>
                </def>
            </entry>

            <entry>
                <form>
                    <orth>ἱεροφόρος</orth>
                    <lang>GR</lang>
                </form>
                <xr>see ἱεραφόρος</xr>
            </entry>

            <entry>
                <form>
                    <orth>ἱεροφυλάκιον, ου</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>τὸ, (ἱεροφύλαξ)</colloc>
                </gramGrp>
                <def>
                    depository of sacred utensils <bibl><author>Dion. Η. Ι</author>, 384. 12.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱεροφύλαξ, ακος</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ὁ, (φύλαξ)</colloc>
                </gramGrp>
                <def>
                    sacrist of a temple. <bibl><author>Dion. H. I</author>, 395, 1.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱεροφωνία, ας</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ἡ</colloc>
                </gramGrp>
                <def>
                    ἱερὰ φωνή. <bibl><author>Eust. Ant.</author> 665 A.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱερόφωνος, ov</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>(φωνή)</colloc>
                </gramGrp>
                <def>
                    Sacred-voiced. Substantively, ὁ ἱερόφωνος, the priest who declares an
                    oracle; essentially ═ υποφήτης. 
                    <bibl>Inscr. 4684, <author>τοῦ κυρίου Σαράπιδος.</author></bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱεροψάλτης, ου</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ὁ</colloc>
                </gramGrp>
                <def>
                    Sacred ψάλτης, psalmist, church-singer. <bibl><author>Sept. Esdr.</author> 1, 1, 14.</bibl>
                    <bibl><author>Jos. Ant.</author> 11, 5, 1, 12, 3, 3, p. 598.</bibl> 
                    <bibl><author>Tit. B.</author> 1245 B.</bibl>
                    <bibl><author>Did. A.</author> 549 A.</bibl>
                    <bibl><author>Quin. Can.</author> 33.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱερόψυχος, ov</orth>
                    <lang>GR</lang>
                </form>
                <def>
                    Sacred ψυχή <bibl><author>Pseudo-Jos. Macc.</author> 17.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱερόω, ώσω</orth>
                    <lang>GR</lang>
                </form>
                <sense n="1">
                    <def>to consecrate.</def>
                </sense>
                <sense n="2">
                    <def>Participle, ἱερωμένος</def>
                    <sense n="(a)">
                        <def>
                            consecrated, sacred. Diod. Ex. Vat. 116, 12. Dion. H. I, 57, 10. 389, 10. Plut. II, 403 F. 981 D. Clem. A. II, 37 C.
                        </def>
                    </sense>
                    <sense n="(b)">
                        <def>
                            priest, clergyman, in Christian writers. <bibl><author>Eus. II</author>, 965 C. <author>IV</author>, 81 C.</bibl> 
                            <bibl><author>Socr.</author> 173 A.</bibl>
                            <bibl><author>Lyd.</author> 253, 5.</bibl>
                            <bibl><author>Justinian Novell.</author> 3, 2, § a’.</bibl>
                        </def>
                    </sense>
                </sense>
                <sense n="3">
                    <def>
                        <cit><quote>Ἱερωμέναι, ἤγουν πρεσβυτέρισσαι, ἢ ἐμβάθμων διακόνων γυναῖκες.</quote> <bibl><author>Jejun.</author> 1921 D. 1912 B</bibl></cit>
                    </def>
                </sense>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱέρωμα, ατος</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>τὁ, (ἱερόω)</colloc>
                </gramGrp>
                <def>
                    thing consecrated to God: offering. <bibl><author>Sept. Macc.</author> 2, 12, 40.</bibl>
                    <bibl><author>Jos, Ant.</author> 1, 19, 11.</bibl> 
                    <bibl><author>Cyrill. A. ΙΙ</author>, 33 B.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>ἱέρωσις, εως</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ἡ</colloc>
                </gramGrp>
                <def>
                    consecration. <bibl><author>Dion C. Frag</author>. 13, 3.</bibl> 
                    <bibl><author>Pseudo-Dion.</author> 124 A.</bibl>
                </def>
            </entry>
            
            <entry>
                <form>
                    <orth> ἱερωσύνη, ης</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
                    <colloc>ἡ</colloc>
                </gramGrp>
                <def>
                    priesthood. 
                    <cit><quote>ἡ μεγίστη, the office of pontifex maximus.</quote> <bibl><author>Classical. Diod. IΙ</author>, 616, 40, App. II, 122, 56.</bibl></cit>
                    The Christian priesthood. 
                    <bibl><author>Epiph.</author> I, 868 D. II, 824 B.</bibl>
                    <bibl><author>Chrys. I,</author> 382 B. </bibl>
                    <bibl><author>Soz.</author> 1032 C.</bibl>
                    Also, ἱεροσύνη. 
                    <bibl><author>Inscr.</author> 2264, p, p. 1036. </bibl>
                    <bibl><author>Strab.</author> 16, 2, 37.</bibl>
                </def>
            </entry>
                
            <entry>
                <form>
                    <orth>Ἰευώ</orth>
                    <lang>GR</lang>
                </form>
                <xr>see Ἰαῶ.</xr>
            </entry>
                
            <entry>
                <form>
                    <orth>ἵζημα, ατος</orth>
                    <lang>GR</lang>
                </form>
                <gramGrp>
